name: Execution

# Controls when the workflow will run.
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      scenarioTag:
        description: 'Scenario Tag to execute(e.g. "@TC-00001")'
        type: string
        required: false
        default: '@Regression'

  schedule:
    # Scheduled the execution.
    # Every day at 9:30 AM (Bolivia).
    - cron: '30 13 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  execution:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      # Cloning you repository to the runner.
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
          architecture: x64

      - name: Install and setup latest Google Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.9
        # Configuration variables in your repository.
        # Settings -> Secrets and variables -> Actions -> Secrets(secrets) or Variables(vars).
      - run: |
          gradle executeFeatures \
              -Dcucumber.filter.tags="${{github.event.inputs.scenarioTag || '@Regression' }}" \
              -Pbrowser="CHROME_HEADLESS" \
              -PbaseUrl="${{vars.BASE_URL}}" \
              -Puser="${{vars.USER_EMAIL}}" -Ppassword="${{secrets.USER_PASSWORD}}" \
              -PapiUrl="${{vars.API_URL}}" \
              -PapiKey="${{secrets.API_KEY}}" -PapiToken="${{secrets.API_TOKEN}}"

      # Upload Allure report.
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allureReport${{github.run_id}}
          path: ./build/allure
          retention-days: 2
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`.

      # Upload log file.
      - name: Upload log file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs${{github.run_id}}
          path: ./logs
          retention-days: 2
