name: Execution

# Controls when the workflow will run.
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      scenarioTag:
        description: 'Scenario Tag to execute(e.g. "@TC-00001")'
        type: string
        required: false
        default: '@Regression'

  schedule:
    # Scheduled the execution.
    # Every friday at 21:00 PM (Bolivia).
    # All the cron job in GitHub Actions is in UTC.
    - cron: '0 1 * * 6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  execution:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    # These permissions are required to generate reports.
    permissions:
      contents: write # To push a branch (gh_pages).

    steps:
      # Cloning you repository to the runner.
      - name: Checkout code
        uses: actions/checkout@v3 # Necessary to access local action.

      - name: Installing the environment
        uses: ./.github/actions/install_environment
        with:
          java-ver: 8
          java-distribution: 'temurin'
          gradle-ver: 6.9

      - name: Execute Features
        uses: ./.github/actions/execute_features
        with:
          scenarioTag: ${{ inputs.scenarioTag || '@Regression' }}
          baseUrl: ${{ vars.BASE_URL }}
          userEmail: ${{ vars.USER_EMAIL }}
          userPassword: ${{ secrets.USER_PASSWORD }}
          apiUrl: ${{ vars.API_URL }}
          apiKey: ${{ secrets.API_KEY }}
          apiToken: ${{ secrets.API_TOKEN }}

      - name: Deploy allure report
        uses: ./.github/actions/deploy_allure_report
        with:
          allure_results_path: ./build/allure/allure-results
          publish_name_branch: gh-pages
